# Generated by Django 4.1.1 on 2022-09-07 21:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(default="", max_length=255)),
                (
                    "opening",
                    models.DecimalField(decimal_places=2, default="", max_digits=10),
                ),
                (
                    "closing",
                    models.DecimalField(decimal_places=2, default="", max_digits=10),
                ),
                ("volume", models.IntegerField(default="")),
                ("trading_day", models.CharField(default="00/00/0000", max_length=255)),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
