# Generated by Django 4.1.1 on 2022-09-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocksapis", "0002_alter_company_closing_alter_company_opening"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="trading_day",
            field=models.CharField(default="00-00-0000", max_length=255),
        ),
    ]
