# Generated by Django 4.1.1 on 2022-09-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocksapis", "0007_alter_company_volume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="volume",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
