# Generated by Django 4.1.1 on 2022-09-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocksapis", "0008_alter_company_volume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="closing",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="company",
            name="company_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="company",
            name="opening",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="company",
            name="trading_day",
            field=models.CharField(max_length=255),
        ),
    ]
